# Generated by Django 3.0.4 on 2020-03-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200309_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
                ('quizanswer', models.ManyToManyField(to='quiz.Question')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
