# Generated by Django 3.0.4 on 2020-03-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200309_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizmakername', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('quizanswer', models.ManyToManyField(to='quiz.Question')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.DeleteModel(
            name='QuizMaker',
        ),
    ]
