# Generated by Django 3.0.4 on 2020-03-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200309_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizMakers',
        ),
        migrations.AlterModelOptions(
            name='quizmakers',
            options={},
        ),
    ]
