# Generated by Django 3.0.4 on 2020-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmakers',
            name='quizanswer',
            field=models.ManyToManyField(blank=True, to='quiz.Question'),
        ),
    ]
