# Generated by Django 3.0.4 on 2020-03-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200309_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmakers',
            old_name='quizanswer',
            new_name='quizques',
        ),
    ]
