# Generated by Django 3.0.4 on 2020-03-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200309_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Option',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='option',
        ),
    ]
