# Generated by Django 3.0.4 on 2020-03-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200310_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
